service: hrms-backend-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  environment:
    MONGODB_URL: ${env:MONGODB_URL}
   

functions:
  app:
    handler: index.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-dotenv-plugin
